 - apt update 
 - apt upgrade
 - apt install python
 - apt install python2
 - pip install requests
 - pip2 install mechanize
 - pkg install git
 - git https://github.com/hackermin991898/hackermin991898/HackerMin.git
 - cd HackerMin
 - ls
 - chmod +x +
 - python2 hackermin.py
