#!/data/data/com.termux/files/usr/bash
echo $red 
 echo ""----------------------------------------------------------------------------- ""
echo " This Script is written by Facebook channel. enjoy"
echo "---------------------------------------------------------------------------------"

echo

echo  "#####################################"
echo   "   MYANMAR     "               
 echo   " HACKER MIN  "                                                                    
echo   "####################################"

echo
echo
echo
echo

echo "."

apt update -y                      #update in progress
apt install python -y           #installation......
apt install python2 -y
apt install ruby -y 
apt install git -y

echo  "#####################################"
echo   "   MYANMAR      "               
 echo   " HACKER MIN "                                                                    
echo   "####################################"

apt install php -y 
apt install perl -y
apt install nmap -y

echo  "#####################################"
echo   " MYANMAR "
  echo "  HACKER MIN  "           
                                                                 
echo   "####################################"

apt install bash -y
apt install clang -y
apt install jq -y
apt install macchanger -y

echo  "#####################################"
echo   "   MYANMAR    "               
 echo   " HACKER MIN "                                                                    
echo   "####################################"

apt install nano -y
apt install curl -y
apt install tar -y
apt install zip -y

echo  "#####################################"
echo   "    MYANMAR      "               
 echo   " HACKER MIN "                                                                    
echo   "####################################"

apt install unzip -y
apt install tor -y
apt install wget -y

echo  "#####################################"
echo   "    MYANMAR     "               
 echo   " HACKER MIN  "                                                                    
echo   "####################################"

apt install wcalc -y 
apt install openssl
apt install bmon -y

echo  "#####################################"
echo   "  MYANMAR      "               
 echo   " HACKER MIN "                                                                    
echo   "####################################"

echo " If You Connected To Internet Then  "
echo " YOUR PACKAGES IS INSTALLED SUCCESSFULLY "

exit
